source 'http://rubygems.org'

gem 'rake'
gem 'sinatra', require: 'sinatra/base'
gem 'minitest'
gem 'faker'
gem 'slim'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'mongoid'
gem 'html-pipeline', require: 'html/pipeline'
gem 'rack-test', require: 'rack/test'
gem 'twitter'
gem 'koala'
