development:
  sessions:
    default:
      database: focacha_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      database: focacha_production
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: focacha_test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false
