development:
  sessions:
    default:
      database: focacha_development
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: focacha_production
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: focacha_test
      hosts:
        - localhost:27017
